name: go-application

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build_metadata:
    uses: nodis-com-br/gha_workflow-jobs/.github/workflows/build_metadata.yaml@master
  test_code:
    uses: nodis-com-br/gha_workflow-jobs/.github/workflows/testing.yaml@master
    needs:
      - build_metadata
    secrets:
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
      vault_addr: ${{ secrets.VAULT_ADDR }}
      vault_approle_role_id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault_approle_secret_id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  build_artifact:
    uses: nodis-com-br/gha_workflow-jobs/.github/workflows/publish_go_application.yaml@master
    needs:
      - build_metadata
  revert_bump:
    uses: nodis-com-br/gha_workflow-jobs/.github/workflows/revert_bump.yaml@master
    needs:
      - build_artifact
    if: always()
    with:
      build_result: ${{ needs.build_artifact.result }}