name: publish

on:
  push:
    branches:
      - master
      - main
      - legacy/*
  pull_request:
    branches:
      - master
      - main
      - legacy/*

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  start:
    uses: ptonini/gha-workflows/.github/workflows/start.yaml@main
  
  publish_artifact:
    uses: ptonini/gha-workflows/.github/workflows/publish-go-application.yaml@main
    needs:
      - start
      - release_please
    with:
      release_created: ${{ needs.release_please.outputs.release_created }}
      tag_name: ${{ needs.release_please.outputs.tag_name }}
  
  quality_scan:
    uses: ptonini/gha-workflows/.github/workflows/code-testing.yaml@main
    if: needs.start.outputs.skip_tests == 'false'
    needs:
      - start
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  code_linting:
    uses: ptonini/gha-workflows/.github/workflows/code-linting.yaml@main
    if: needs.start.outputs.housekeeping == 'true'
    needs:
      - start
  security_leaks_scan:
    uses: ptonini/gha-workflows/.github/workflows/trufflehog.yaml@main
    if: needs.start.outputs.housekeeping == 'true'
    needs:
      - start